name: radar-cookbook-dev
channels:
  - conda-forge
  - pyviz
dependencies:
  - python
  - jupyter-book
  - jupyterlab
  - matplotlib
  - cartopy
  - jupyter_server
  - numpy<2.0
  - xarray
  - metpy
  - act-atmos>=1.2.0
  - imageio
  - arm_pyart
  - hvplot
  - datashader
  - panel
  - sphinx-pythia-theme
  - mystmd
  - nodejs
  - s3fs>=2024.3.1
  - pip
  - pip:
    - fast-barnes-py
    - git+https://github.com/vlouf/eth_radar.git
    - open-radar-data>=0.1.2
